### ISSUE TITLE
Redirecting Issues - When I click on submit of course creation, its redirecting to IP http://192.168.0.106:8080/content/content_creator/module_list.jsp to http://localhost:8080/content/content_creator/edit_module.jsp?module_id=2  || Session

### ISSUE THREAD

**Issue by vinayistar** [ISTARSkills/istarissues#327] opened 2017-05-04 11:29 UTC
Redirecting to localhost every time and still creating course in IP 192.168.0.106

![image](https://cloud.githubusercontent.com/assets/16954148/25701464/2432b856-30ea-11e7-87cd-7e03d6e5f140.png)

**Comment by absin1** [comment] 2017-05-04 11:43
The issue is that I have mentioned localhost:8080..... in the redirect path, which should be corrected in all the places where redirection happens; once I do that, I will close this issue.

**Comment by absin1** [comment] 2017-05-05 06:53
Fixed

**Closed by absin1** 2017-05-05 06:53 UTC
Labels: bug, CMS
